baseURL = 'https://poltimmer.github.io/'
languageCode = 'en-us'
title = 'Pol Timmer'

theme = "digitalgarden"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'My Research'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Other Stuff'
  params.header = true
  weight = 4
[[menu.main]]
  name = 'My Resume'
  url = '/pdf/resume.pdf'
  weight = 5

[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/pol-timmer/'
  weight = 1

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/poltimmer'
  weight = 2

[[menu.social]]
  name = 'Email'
  url = 'mailto:pol.timmer@gmail.com'
  weight = 3


[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true